config/routes.rb
Rails.application.routes.draw do
  get 'search', to: 'search#index'

  devise_for :users
  resources :downloads
  resources :books do 
    resources :reviews
  end

  root to: 'books#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :downloads
  has_many :reviews
  belongs_to :user
  belongs_to :category

  has_one_attached :image
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :books
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews
  has_many :books
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  enum role: [:user, :admin]
  after_initialize :set_default_role, :if => :new_record?
  def set_default_role
    self.role ||= :user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
  before_action :set_query

  def set_query
     @query =  Book.ransack(params[:q])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :find_book, only: [:show, :edit, :update, :destroy]

  def index
    if params[:category].blank?
      @books = Book.all.order("created_at DESC")
    else
      @category_id = Category.find_by(name: params[:category]).id
			@books = Book.where(:category_id => @category_id).order("created_at DESC")
    end
  end

  def show
    @book = Book.find(params[:id])
    fresh_when etag: @book
  end
  
  def new
    @book = Book.new
    @categories = Category.all.map{ |c| [c.name, c.id] }
  end

  def create
    @book = Book.new(book_params)
    @book.category_id = params[:category_id]
    if @book.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @categories = Category.all.map{ |c| [c.name, c.id] }
  end

  def destroy
		@book.destroy
		redirect_to root_path
	end

  def update
    @book.category_id = params[:category_id]
    if @book.update(book_params)
      redirect_to book_path(@book)
    else
      render 'edit'
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :description, :author, :category_id, :image, :price, :content)
  end

  def find_book
    @book = Book.find(params[:id])
  end
end

app/controllers/downloads_controller.rb
class DownloadsController < ApplicationController
  def index
    @books = Book.all
  end

  def show
     @book = Book.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_book
	before_action :find_review, only: [:edit, :update, :destroy]
	before_action :authenticate_user!, only: [:new, :edit]

	def new
		@review = Review.new
	end

	def create
		@review = Review.new(review_params)
		@review.book_id = @book.id
		@review.user_id = current_user.id

		if @review.save
			redirect_to download_path(@book)
		else
			render 'new'
		end
	end

  def show
    if @books.reviews.blank?
      @average_review = 0
    else
       @average_review = @book.reviews.average(:rating).round(2)
    end
  end

	def edit
	end

	def update
		if @review.update(review_params)
			redirect_to download_path(@book)
		else
			render 'edit'
		end
	end

	def destroy
		@review.destroy
		redirect_to download_path(@book)
	end

	private

		def review_params
			params.require(:review).permit(:rating, :comment)
		end

		def find_book
			@book = Book.find(params[:book_id])
		end

		def find_review
			@review = Review.find(params[:id])
		end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @query =  Book.ransack(params[:q])
    @books = @query.result(distinct: true)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/downloads_helper.rb
module DownloadsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/books/_form.html.erb
<div class="links">
  <%= simple_form_for @book, :html => { :multipart => true }  do |f| %>
    <%= select_tag(:category_id, options_for_select(@categories), :prompt => "select category book")%>
    <%= f.file_field :image %>
    <%= f.input :title, label: "Book Title"%>
    <%= f.input :description%>
    <%= f.input :author%>
    <%= f.number_field :price%>
    <%= f.input:content, as: :text%>
  
    <%= f.button :submit, :class => 'btn-custom-submit'%>
  <% end %>
</div>

app/views/books/edit.html.erb
<div class="col-md-6 col-md-offset-3">

	<div class="edit-book-form">
    
    <div class="links">
      <h1>Edit Book</h1>

      <%= simple_form_for @book, :html => { :multipart => true } do |f| %>
        <%= f.select :category_id, @categories%>
        <%= f.file_field :image %>
        <%= f.input :title, label: "Book Title"%>
        <%= f.input :description%>
        <%= f.input :author%>
        <%= f.number_field :price%>
        <%= f.input :content, as: :text %>
      
        <%= f.button :submit, :class => 'btn-custom-submit'%>
      
      <% end %>
    </div>

	</div>

</div>

app/views/books/index.html.erb
<div class="container">
  <h1 class="current-category"><%= params[:category] %></h1>
  
  <% if current_user %>
    <p align='center'> Hi <%= current_user.email.split('@')[0].capitalize %> welcome to our book store <%= image_tag "blob-attention-gif", height: 27 %></p>
  <% end %>
    
  <% if @books.count > 0 %>
  
    <% if user_signed_in? %>
      <% if current_user %>
        <% if current_user.admin? or current_user.user? %>
          <table class="table table-dark table-sm table-bordered">
            <thead>
              <tr>
                <th scope="col">Book Cover</th>
                <th scope="col">Title</th>
                <th scope="col">Author</th>
                <th scope="col">Price</th>
              </tr>
            </thead>
            <tbody>
              <% @books.each do |book| %>
                <tr>
                  <td align="center"> <a href=/books/<%= book.id %>"><%= image_tag book.image, class:"book-admin" %></a></td>
                  <td><%= link_to book.title, book_path(book) %></td>
                  <td><%= book.author %></td>
                  <td>$<%= book.price %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        <% end %>
      <% end %>
    <% else %>
      <% @books.each do |book| %>
         <div class="col-md-3">
            <a href="/books/<%= book.id %>" data-bs-toggle="popover" title="<%= book.title %>">
              <%= image_tag book.image, class:"book" %>
              <!-- <figcaption><%= book.title %></figcaption> -->
            </a>
          </div>
      <% end %>
    <% end %>
  
  <% else %>
  
    <h1>There are no books currently in this category</h1>
    
  <% end %>
</div>
  

app/views/books/new.html.erb
<div class="col-md-6 col-md-offset-3">

	<div class="new-book-form">

		<h1>New Book</h1>

		<%= render 'form' %>

	</div>

</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row align-items-center">
    <div class="col-md-4 offset-md-3">
      <% if @book.image.attached? %>
        <%= image_tag @book.image, class:"book-show"%>
      <% end %>
      <div class="links">
        <%= link_to "Back", root_path, class: "btn btn-custom"%>
          
        <% if user_signed_in? %>
          <% if current_user %>
            <% if current_user.admin? %>
              <%= link_to "Edit", edit_book_path(@book), class:'btn btn-custom-edit' %>
              <%= link_to "Delete", book_path(@book),data: { confirm: "Are you sure?" }, method: :delete, class:'btn btn-custom-delete' %>
                <%= link_to "Download", download_path(@book) , class: "btn btn-custom-download"%>
            <% else %>
              <button type="button" class="btn btn-custom-download" data-toggle="modal" data-target="#Modal">Download</button>
              <!-- Modal -->
              <div class="modal fade" id="Modal" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="ModalLabel">Want Read This Book?</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-body">
                      <p>buy this for only $<%=@book.price%></p>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                      <%= link_to "Buy", download_path(@book), class: "btn btn-primary"%>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          <% end %>    
        <% end %>
      </div>
      <div class="book-info-review">
        <%= render @book.reviews %>
      </div>
    </div>
  
    <div class="col-md-8">
      <div class="book-info">
        <h1 class="book-title"><%= @book.title%></h1>
        <h3 class="book-category"><%= @book.category.name %></h3>
        <div class="average-review-rating" data-score = <%= @average_review %>></div>
  			<span class="number-of-reviews">Based on <%= @book.reviews.count %> reviews</span>
        <p class="book-desc"><%= @book.description %></p>
        <h3 class="book-author"><span> From : </span><%= @book.author %></h3>
      </div>
    </div>
  </div>
</div>
          \
<script>
	$('.review-rating').raty({
		readOnly: true,
		score: function() {
			return $(this).attr('data-score');
		},
		path: '/assets/'
	});
</script>

<script>
	$('.average-review-rating').raty({
		readOnly: true,
		path: '/assets/',
		score: function() {
			return $(this).attr('data-score')
		}
	});
</script>

app/views/downloads/index.html.erb
<h1>Downloads#index</h1>

app/views/downloads/show.html.erb
<div class="container">
  <div class="row align-items-center">
    <div class="col-md-4 offset-md-3">
      <% if @book.image.attached? %>
        <%= image_tag @book.image, class:"book-show"%>
      <% end %>
      <div class="links">
        <%= link_to "Back", book_path(@book), class: "btn btn-custom"%>
      </div>
      <div class="book-info-review">
        <%= render @book.reviews %>
        <div class="links btn-group">
           <%= link_to "Add Reviews", new_book_review_path(@book), class: "btn btn-custom" %>
        </div>
      </div>
    </div>
  
    <div class="col-md-8">
      <div class="book-info">
        <h1 class="book-title"><%= @book.title%></h1>
        <h3 class="book-category"><%= @book.category.name %></h3>
        <div class="average-review-rating" data-score = <%= @average_review %>></div>
         <span class="number-of-reviews">Based on <%= @book.reviews.count %> reviews</span>
        <p class="book-desc"><%= @book.description %></p>
        <h3 class="book-author"><span> From : </span><%= @book.author %></h3>
      </div>
      <div class="book-info-content">
        <p class="book-content"><%= @book.content %></p>
      </div>
    </div>
        
  </div>
</div>

<script>
	$('.review-rating').raty({
		readOnly: true,
		score: function() {
			return $(this).attr('data-score');
		},
		path: '/assets/'
	});
</script>


<script>
	$('.average-review-rating').raty({
		readOnly: true,
		path: '/assets/',
		score: function() {
			return $(this).attr('data-score')
		}
	});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sprinkle Book Store</title>
    <link rel = "icon" type = "image/png" href="/assets/icon-sprinkle.png" >
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar-default">
      <div class="container">
        <div class="navbar-header">
          <a href="/books">
            <%= image_tag "sprinkle-logo", class: "navbar-brand" %> 
          </a>
        </div>

        <ul class="nav navbar-nav navbar-right">
				  <% if user_signed_in? %>
            <li><%= render 'search/form' %></li>
					  <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            <li><%= link_to "Edit #{current_user.role}", edit_user_registration_path%></li>
				  <% else %>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
					  <li><%= link_to "Log In", new_user_session_path%></li>
				  <% end %>
        </ul>

        <ul class="nav navbar-nav">
          
          <li class="dropdown">
  					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Categories <span class="caret"></span></a>
  					<ul class="dropdown-menu" role="menu">
  						<% Category.all.each do |category| %>
  							<li class="<%= 'active' if params[:category] == category.name %>">
  								<%= link_to category.name, books_path(category: category.name), class: "link" %>
  							</li>
  						<% end %>
  					</ul>
				  </li>
              
				  <% if user_signed_in? %>
            <% if current_user.admin? %>
					    <li><%= link_to "Add Book", new_book_path%></li>
            <% end %>
          <% end %>
        </ul>

      </div>
    </nav>

    <div class="container">
      <% if current_user %>
        <% if current_user.admin? %>
          <p>You are an <%= current_user.role %>
            and there are <%= User.count %> users in this sistem
          </p>
        <% end %>
      <% end %>
    </div>
    
    <%= yield %>
      
  </body>
</html>

app/views/reviews/_form.html.erb
<%= simple_form_for([@book, @book.reviews.build]) do |f| %>
	<div id="rating-form">
		<label>Rating</label>
	</div>
	<%= f.input :comment %>
  <div class="links"> 
    <%= f.button :submit, :class => "btn btn-custom-submit" %>
  </div>
	
<% end %>

<script>
	$('#rating-form').raty({
		path: '/assets/',
		scoreName: 'review[rating]'
	});
</script>

app/views/reviews/_review.html.erb
<div class="review">
  <div class="review-rating" data-score="<%= review.rating %>"></div>
  <p class="review-comment"><%= review.comment %></p>
</div>	

<% if user_signed_in? %>
  <% if review.user_id == current_user.id %>

    <div class="links">
      <%= link_to "Edit", edit_book_review_path(review.book, review), class: "btn btn-custom-edit" %>
      <%= link_to "Delete", book_review_path(review.book, review), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-custom-delete" %>
    </div>
  
  <% end %>	
<% end %>	

<p>--------------------------------------------------------------</p>

app/views/reviews/edit.html.erb
<div class="col-md-6 col-md-offset-3">

	<div class="edit-review-form">

		<h1>Edit Review</h1>

		<%= simple_form_for([@book, @review]) do |f| %>
			<div id="rating-form">
				<label>Rating</label>
			</div>
			<%= f.input :comment %>
			<%= f.button :submit, :class => "btn-custom2" %>
		<% end %>	

	</div>

</div>

<script>
	$('#rating-form').raty({
		path: '/assets/',
		scoreName: 'review[rating]'
	});
</script>

app/views/reviews/new.html.erb
<div class="col-md-6 col-md-offset-3">

	<div class="new-review-form">

		<h1>New Review</h1>

		<%= render 'form' %>

	</div>

</div>

app/views/search/_form.html.erb
<div class="col-xs-11" >
  <div class="form-group has-feedback">
    <%= search_form_for(@query, url: search_path, method: :get, class: 'd-flex') do |f| %>
      <%= f.search_field :title_or_author_or_price_i_cont_any, placeholder: "Search Title, Author or Price", class:"form-control" %>
      <span class="glyphicon glyphicon-search form-control-feedback"></span>
    <% end %>
  </div>
</div>

app/views/search/index.html.erb
<div class="container">
  <table class="table table-dark table-sm table-bordered">
    <thead>
      <tr>
        <th scope="col">Book Cover</th>
        <th scope="col">Title</th>
        <th scope="col">Author</th>
        <th><%= sort_link(@query, :price, "Price")%></th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
        <tr>
          <td align="center"> <a href=/books/<%= book.id %>"><%= image_tag book.image, class:"book-admin" %></a></td>
          <td><%= link_to book.title, book_path(book) %></td>
          <td><%= book.author %></td>
          <td>$<%= book.price %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="links">
    <%= link_to "Back", root_path, class: "btn btn-custom"%>
  </div>
</div>